#!/bin/bash

#brctl addbr br0
#brctl addif br0 enp34s0
#ip a add 192.168.1.5/24 dev br0
#ip link set br0 up
#route add -net 192.168.1.0 netmask 255.255.255.0 br0
#route add default gw 192.168.1.254 br0

ip tuntap add tap1 mode tap
ip link set tap1 down
brctl addif br0 tap1
ip link set tap1 up

sleep 10
sysctl -w net.ipv4.ip_forward=1
